#####  TOKEN TYPES  #####

##  MATH TOKENS  ##

TT_INT = "INT"
TT_FLOAT = "FLOAT"
TT_PLUS = "PLUS"
TT_MINUS = "MINUS"
TT_MUL = "MUL"
TT_DIV = "DIV"
TT_POWER = "POWER"
TT_MOD = "MOD"
TT_LPAREN = "LPAREN"
TT_RPAREN = "RPAREN"

##  BOOLEAN TOKENS  ##

TT_GREATER_THAN = "GREATER_THAN"
TT_LESS_THAN = "LESS_THAN"
TT_GREATER_OR_EQ_TO = "GREATER_OR_EQ_TO"
TT_LESS_OR_EQ_TO = "LESS_OR_EQ_TO"
TT_EQ_TO = "EQ_TO"
TT_NOT_EQ_TO = "NOT_EQ_TO"
TT_TRUE = "TRUE"
TT_FALSE = "FALSE"
TT_NULL = "NULL"
COMP_OPS = (TT_GREATER_THAN, TT_LESS_THAN, TT_GREATER_OR_EQ_TO, TT_LESS_OR_EQ_TO, TT_EQ_TO, TT_NOT_EQ_TO)

##  LOGICAL OPERATIONS  ##

TT_AND = "AND"
TT_OR = "OR"
TT_NOT = "NOT"

##  VARIABLE TOKENS  ##

TT_IDENTIFIER = "IDENTIFIER"
TT_KEYWORD = "KEYWORD"
TT_EQ = "EQ"

##  MISC TOKENS ##

TT_EOF = "EOF"